<?php
# This file was automatically generated by the MediaWiki 1.37.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "H&D Publishing Wiki";
$wgMetaNamespace = "H&D_Publishing_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki2print.hackersanddesigners.nl";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO


$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "karl@hackersanddesigners.nl"; ## use your own email address
$wgPasswordSender   = "karl@hackersanddesigners.nl"; ## use your own email address
$wgNoReplyAddress   = "karl@hackersanddesigners.nl"; ## use your own email address

$wgSMTP = [
  'host'     => 'ssl://smtp.migadu.com',       ## hostname of the email server
  'IDHost'   => 'smtp.migadu.com',             ## these options could all
  'port'     => 465,                           ## be different for you
  'auth'     => true,                          ## especially these ones:
  'username' => 'karl@hackersanddesigners.nl', ## use your own email account
  'password' => 'flick-granular-spiritual'     ## @andre @hrk ignore :/
];

$wgEnotifUserTalk      = true;
$wgEnotifWatchlist     = true;
$wgEmailAuthentication = true;
$wgEmailConfirmToEdit  = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki2printDB";
$wgDBuser = "wiki2printUSER";
$wgDBpassword = "wikiprintingisfun";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "Europe/Berlin";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "583dd3bfac7674348aff35411a7f976bb93b5011b580746d1bde8d5d5db90f70";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "90f5bdd39e95de5c";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "Creative Commons Attribution-NonCommercial-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
#$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );


# End of automatically generated settings.
# Add more configuration options below.

# ConfirmAccount: requiring the approval of new accounts by a bureaucrat
wfLoadExtension( 'ConfirmAccount' );

$wgMakeUserPageFromBio            = false;
$wgConfirmAccountRequestFormItems = [
	'UserName'        => [ 'enabled' => true ],
	'Biography'       => [ 'enabled' => false, 'minWords' => 50 ],
 	'AreasOfInterest' => [ 'enabled' => false ],
 	'CV'              => [ 'enabled' => false ],
 	'Notes'           => [ 'enabled' => true ],
 	'Links'           => [ 'enabled' => false ],
	'TermsOfService'  => [ 'enabled' => true ],
];
$wgConfirmAccountContact = 'karl@hackersanddesigners.nl'; ## use your own email address
$wgGroupPermissions['bureaucrat']['confirmaccount-notify'] = true;

# UserMerge: merging ('deleting') users

wfLoadExtension( 'UserMerge' );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

# Custom publishing namespace

define("NS_Publishing", 3000);
define("NS_PublishingCSS", 3001); # bad practice!
define("NS_PublishingJS", 3002); # bad practice!
$wgExtraNamespaces[NS_Publishing] = "Publishing";
$wgExtraNamespaces[NS_PublishingCSS] = "PublishingCSS";
$wgExtraNamespaces[NS_PublishingJS] = "PublishingJS";
$wgNamespacesWithSubpages[NS_Publishing] = true;
$wgNamespacesWithSubpages[NS_PublishingCSS] = true;
$wgNamespacesWithSubpages[NS_PublishingJS] = true;


# We change the content model of the CSS and JS namespaces from the default WIKITEXT.
# The forces the CodeEditor to replace the VisualEditor for better legibility.
$wgNamespaceContentModels[NS_PublishingCSS] = CONTENT_MODEL_CSS;
$wgNamespaceContentModels[NS_PublishingJS] = CONTENT_MODEL_JAVASCRIPT;


# We need to force the VisualEditor to exist in our Publishing namespace.
$wgVisualEditorAvailableNamespaces = [
  'Publishing' => true
];

# Custom skin

wfLoadSkin( 'Citizen' );
$wgDefaultSkin = "citizen";
